import '@/styles/globals.css'
import '@/styles/variables.css'

import type { Metadata } from 'next'
import localFont from 'next/font/local'

import { Footer } from '@/components/layout/Footer/Footer'
import { Header } from '@/components/layout/Header/Header'
import { Main } from '@/components/layout/Main/Main'
import { Noise } from '@/components/ui/Noise/Noise'
import { cn } from '@/lib/cn'

import styles from './layout.module.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const bounded = localFont({
	src: '../fonts/Bounded-Variable.ttf',
	variable: '--font-bounded',
})

const velaSans = localFont({
	src: '../fonts/VelaSans-GX.ttf',
	variable: '--font-vela-sans',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={cn(bounded.variable, velaSans.variable)}>
				<div className={styles.app}>
					<Noise />
					<Header />
					<Main>{children}</Main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
