import '@/styles/globals.css'
import '@/styles/variables.css'

import type { Metadata } from 'next'
import { IBM_Plex_Sans } from 'next/font/google'

import { Footer } from '@/components/layout/Footer/Footer'
import { Header } from '@/components/layout/Header/Header'
import { Main } from '@/components/layout/Main/Main'
import { LinesOverlay } from '@/components/ui/LinesOverlay/LinesOverlay'

import styles from './layout.module.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const fontIBM = IBM_Plex_Sans({
	subsets: ['cyrillic'],
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={fontIBM.className}>
				<div className={styles.app}>
					<LinesOverlay />
					<Header />
					<Main>{children}</Main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
