import '@/styles/globals.css'
import '@/styles/variables.css'

import type { Metadata } from 'next'
import { Oswald, Rubik } from 'next/font/google'

import { Footer } from '@/components/layout/Footer/Footer'
import { Header } from '@/components/layout/Header/Header'
import { Main } from '@/components/layout/Main/Main'
import { Noise } from '@/components/ui/Noise/Noise'
import { cn } from '@/lib/cn'

import styles from './layout.module.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const oswald = Oswald({
	subsets: ['cyrillic'],
	display: 'swap',
	variable: '--font-oswald',
})

const rubik = Rubik({
	subsets: ['cyrillic'],
	display: 'swap',
	variable: '--font-rubik',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={cn(oswald.variable, rubik.variable)}>
				<div className={styles.app}>
					<Noise />
					<Header />
					<Main>{children}</Main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
